const systemText = {
    ko: {
        'myName': '양준형',
        'frontEndDevloper': '프론트엔드 개발자',
        'about': '소개',
        'profile': '프로필',
        'workExperience': '경력사항',
        'skills': '스킬',
        'study': '교육',
        'projects': '프로젝트',
        'contact': '문의',

        'address': '주소',
        'myAddress': '아일랜드 더블린',
        'phone': '전화번호',
        'myPhone': '010-9164-1201',
        'email': '이메일',
        'myEmail': 'y.junh0y@gmail.com',
        'aboutMe': '안녕하세요. 프론트엔드 개발자 양준형입니다. JAVA 풀스택 과정 수료 후 <span class="bold">프론트엔드</span> 개발 담당(PHP, Laravel)으로 2년 간 플랫폼 사이트를 구축했습니다. 해당 플랫폼과 관련하여 이전의 경력을 바탕으로 프론트엔드뿐만 아니라 <span class="bold">웹 기획, DB 설계, 백엔드(API 개발)</span> 업무도 담당했습니다.',
        'content': '내용',
        'sendEmail': '이메일 발송',
        'emailAlert': '이메일 주소를 입력하세요.',
        'contentAlert': '내용을 입력하세요.',
        'sendSuccess': '이메일 발송이 완료되었습니다.',

        'ctk': '씨티케이',
        'ctkCosmetics': '씨티케이 코스메틱스',
        'ctkClip': 'CTKCLIP',
        'forPartner': '파트너 사이트',
        'forAdmin': '어드민 사이트',

        'ctkDate': '2022.04 - 2024.04',
        'ctkRole': '프론트엔드 개발자 / 매니저',
        'ctkDescription': '· 플랫폼 사이트 개발 및 유지보수 (PHP, Laravel) </br>· 플랫폼 파트너 사이트 개발 및 유지보수 (vue.js) <br/>· 성분 스크리닝 페이지 기획 및 개발',

        'innerbottle': '이너보틀',
        'innerbottleDate': '2019.06 - 2021.06',
        'innerbottleRole': '선임연구원',
        'innerbottleDescription': '· 제품 개발 및 품질 업무 담당 <br />· 생산 기술 개발 및 공정 확립',

        'viewProjects': '프로젝트 보기',
        'goToTheSite': '사이트 이동',

        'portfolio': '포트폴리오',
        'portfolioDesc': '개인 포트폴리오 사이트',

        'frontEnd': '프론트엔드',
        'backEnd': '백엔드',
        'others': '기타',
        'languages': '언어',
        'korean': '한국어 (원어민)',
        'english': '영어 (중급)',
        'englishExtra1': '· 전시회 고객 응대 (코스모프로프 2019, 2022)',
        'englishExtra2': '· 외부 API 관련 이메일 소통',

        'kosmo': '한국소프트웨어인재개발원',
        'kosmoDate': '2021.09 - 2022.03',
        'kosmoDesc': '풀스택 과정 수료 및 개발 프로젝트 수행',

        'hongik': '홍익대학교',
        'hongikDate': '2010.03 - 2017.02',
        'hongikMajor': '기계시스템디자인공학 (학사)',
        'hongikMinor': '도예유리 (부전공)',
    },
    en: {
        'myName': 'Jun Hyeong Yang',
        'frontEndDevloper': 'Front-end Developer',
        'about': 'About',
        'profile': 'Profile',
        'workExperience': 'Work Experience',
        'skills': 'Skills',
        'study': 'Study',
        'projects': 'Projects',
        'contact': 'Contact',
        'sendEmail': 'Send an email',

        'address': 'Address',
        'myAddress': 'Dublin, Ireland',
        'phone': 'Phone',
        'myPhone': '010-9164-1201',
        'email': 'Email',
        'myEmail': 'y.junh0y@gmail.com',
        'aboutMe': 'Hello. I am Junhyeong Yang, a front-end developer. After completing a full-stack development course, I have spent the past two years building a platform site as a <span class="bold">front-end development</span>(PHP, Laravel). Leveraging my previous experience in the related industry, I have handled not only front-end development but also <span class="bold">web planning, database design, and back-end</span> (API development) tasks.',
        'content': 'Content',
        'emailAlert': 'Please enter an email address.',
        'contentAlert': 'Please enter content.',
        'sendSuccess': 'The email has been sent successfully.',

        'ctk': 'CTK',
        'ctkCosmetics': 'CTK Cosmetics',
        'ctkClip': 'CTKCLIP',
        'forPartner': 'for Partner',
        'forAdmin': 'for Admin',

        'ctkDate': 'APR 2022 - APR 2024',
        'ctkRole': 'Front-end Developer / Assistant Manager',
        'ctkDescription': '· Developed and maintained 3 sites with PHP(Laravel) & 1 site with vue.js <br />· Planned, developed and maintained an ingredients screening page',

        'innerbottle': 'Innerbottle',
        'innerbottleDate': 'JUN 2019 - JUN 2021',
        'innerbottleRole': 'Researcher',
        'innerbottleDescription': '· Researched, devloped and assured quality to cosmetic packages. <br />· Developed and improved a production technology & process',

        'viewProjects': 'View projects',
        'goToTheSite': 'Go to the site',

        'portfolio': 'Portfolio',
        'portfolioDesc': 'Personal portfolio site',

        'frontEnd': 'Front-end',
        'backEnd': 'Back-end',
        'others': 'Others',
        'languages': 'Langauges',
        'korean': 'Korean (Native)',
        'english': 'English (Intermediate)',
        'englishExtra1': '· Handled customer service at exhibitions (Cosmoprof 2019, 2022)',
        'englishExtra2': '· Communicated via email regarding external APIs',

        'kosmo': 'KOSMO',
        'kosmoDate': 'SEP 2021 - MAR 2022',
        'kosmoDesc': 'Completed a full-stack programming class and developed some projects.',

        'hongik': 'Hongik University',
        'hongikDate': 'MAR 2010 - FEB 2017',
        'hongikMajor': 'Mechanical System Design Engineering (BA)',
        'hongikMinor': 'Ceramic & Class (Minor)',
    },
};

export default systemText;